-- Supprimer des Management Start Date aux comptes suivants

update b_compte set date_incep = null where no_compte = "800251-GT"
update b_compte set date_incep = null where no_compte = "800237-JW"
update b_compte set date_incep = null where no_compte = "800003-NA"
update b_compte set date_incep = null where no_compte = "800003-OB"
update b_compte set date_incep = null where no_compte = "800006-NA"
update b_compte set date_incep = null where no_compte = "800006-GT"
update b_compte set date_incep = null where no_compte = "800257-RE"
update b_compte set date_incep = null where no_compte = "800262-RE"
update b_compte set date_incep = null where no_compte = "800030-NA"
update b_compte set date_incep = null where no_compte = "800030-JW"
update b_compte set date_incep = null where no_compte = "800257-FS"
update b_compte set date_incep = null where no_compte = "800260-RE"
update b_compte set date_incep = null where no_compte = "800259-NA"
update b_compte set date_incep = null where no_compte = "800264-FS"
update b_compte set date_incep = null where no_compte = "800218-NA"
update b_compte set date_incep = null where no_compte = "300002-NA"
update b_compte set date_incep = null where no_compte = "300007-NA"
update b_compte set date_incep = null where no_compte = "800241-GT"