update B_CONFIG set NOTE = 'INCLUDE_USERS=UNI00,COPERN, BELLAL, DARWIC
EXCLUDE_CATEGO=650,470' where CLE = 'FD_COMPLIANCE_TEST_OSSP'

update B_CONFIG set NOTE='40000000' where CLE = 'FD_COMPLIANCE_SECURITY_ALERT_MV'

update B_ASSET set DEFAULT_RATE = 1 where CATEGO =60

GO